### ISSUE TITLE
[Diseño] Cambio general del diseño.

### ISSUE THREAD

**Issue by yuriyfpmislata** [WeekFood/WeekFood#221]
Probar con blanco, negro, rojo. Y con variedades de WeekFood: todo negro, todo blanco, rojo, alternado...

**Comment by Hechix** [comment]
Imagen que hemos probado para el fondo:
![](https://thetangerinebowl.com/wp-content/uploads/2014/08/light-wood-BK.png)
Imagen que hemos probado del mantel:
![](https://previews.123rf.com/images/stevanovicigor/stevanovicigor1501/stevanovicigor150100042/35095231-red-and-white-checkered-tablecloth-pattern-texture-as-background.jpg)

**Comment by yuriyfpmislata** [comment]
Rojo (aprox, que me salió desenfocadísima la foto xd) mas oscuro que probamos para la cabecera: #cb1e0b
